### PR TITLE
feat: add option for prepending (no)script to body

### PR DESCRIPTION
**Pull request by pimlie**
Resolves: #370

I couldnt came up with a good single name, so I decided on `pody` as in prepended body. 

I am happy to change this to something better, but I'd prefer to keep it to a single word so we dont have kebab/camelCase issues when switching between js object property and html attribute name.

### CODE REVIEW

**Comment by Atinux** [comment]
Nice PR @pimlie 

I don't know what to feel about `pody`, I would have mabe called it `pbody` to keep `body` and `p` for `prepend`.

**Comment by pimlie** [comment]
Renamed `pody` to `pbody`

**Comment by Atinux** [comment]
Good for me (expect failing test 😄 )

**Comment by pimlie** [comment]
Ha, thanks for the heads-up. Getting a bit too used to failing tests due to the IE issue I guess ;)

**Comment by derz** [comment]
thanks for you work @pimlie. Wouldn‘t it be nicer to extend the existing `body` flag and include two options for it - maybe: `afterbegin` and `beforeend` like it is used, for example, in here: https://developer.mozilla.org/de/docs/Web/API/Element/insertAdjacentHTML 
We could use `beforeend` as the default value if it is set to `true` to avoid breaking changes and avoid a potential pitfall if both flags (`body` and pbody`) are set.

**Comment by pimlie** [comment]
@derz Thank you for your comment. I can see the logic in your suggestion. After this PR was merged I realized it would maybe also be nice to just add extra methods, so instead of calling `text()` you'd call `meta.script.body()` / `meta.script.bodyAppend()` vs `meta.script.bodyPrepend()`

But I am not strongly opinionated on the matter, so I will leave the initiative to change this API to someone else :)

**Pull request merged**
