### PR TITLE
chore: add next/edge release configs

### PR DESCRIPTION
**Pull request by pimlie**
Ref: #330

### CODE REVIEW

**Comment by pi0** [comment]
Is this PR appending prefix to package name before release?

**Comment by pimlie** [comment]
That was still an open question indeed, for now it just uses prerelease package versions and tags. Eg `vue-meta@next`, `vue-meta@edge` and `vue-meta@2.0.0-25888327.3c50876d`

**Comment by pi0** [comment]
PLEASE STOP RELEASING

**Comment by pimlie** [comment]
- 269ed9b was a succesful test for manual releases
- fcb2797 was a succesfull test for nightly releases

Because vue-meta wont probably be as active as nuxt, nightly releases should only be released when there have been any commits on the branch (but this I havent been able to test)

`dry-run` is still set on `npm publish`, feel free to remove it when you approve this pr

**Comment by manniL** [comment]
cc @pi0

**Comment by pimlie** [comment]
I am closing this pr for now in favor of manual releases. Have been working on some scripts to do this better, but those will take some more time to mature and dont want to hold-up the rc any longer

**Pull request closed without merging**
