### PR TITLE
feat: add possibility to add additional  meta info

### PR DESCRIPTION
**Pull request by pimlie**
refactor: server injectors
feat: add head, bodyPrepend, bodyAppend injectors
feat: add possible line break after generated tags (easier debugging)
refactor: create browserbuild through rollup replace (not separate entry)

### Adding additional meta info

(@kevinmarrec please check if this could solve the vuetify issue)

Example of adding additional meta info for eg a third party plugin:

```js
const { set, remove } = app.$meta().addApp('custom')

set({
  meta: [{ charset: 'utf=8' }]
})

setTimeout(() => remove(), 3000)
```

There is no reactivity for custom apps. You need to take care of that and call `set` and `remove` when apropiate. If you call `addApp.set` on the client before the app is mounted, the tags will be processed on the first refresh. If you call set when the app is mounted they tags are immediately processed.

The function is called addApp because the added metaInfo is treated exactly the same as when there are multiple apps on one page. Eg the tags that will be added will also list the `appId` you specifiy:
```html
<meta data-vue-meta="custom" charset="utf-8">
```

~~Btw, multiple apps (still) dont support adding html/head/body attributes by multiple apps. Only one app can do that because otherwise they will be overwritten. Still looking for a nicer solution then adding all kinds of data attributes to the tags.~~

### Add injector helpers

So templates can be a little less verbose:

Old: https://github.com/nuxt/vue-meta/blob/master/examples/ssr/app.template.html
New: https://github.com/nuxt/vue-meta/blob/feat-add-non-component-info/examples/ssr/app.template.html

### Add line break (server side only)

Resolves: #432

Pass either a boolean `true` to `inject().head(true)`, `inject().bodyPrepend(true)` or `inject().bodyAppend(true)` to insert a linebreak after all tags.

If you want to keep using the old syntax, pass a prop `ln: true` as arg: `meta.script.text({ body: true, ln: true })`

### CODE REVIEW

**Comment by Atinux** [comment]
Nice work here @pimlie 

Does it open a breaking change for the injector helpers?

**Comment by pimlie** [comment]
### Support setting attributes from multiple apps

I have changed the behaviour that vue-meta always adds `data-` attributes to track attributes on the client side. Instead of a data attribute we just keep a local attributeMap object in the attribute updater which also adds support for updating attributes from multiple apps. To track this data from a ssr page, the data- tag is still added but with a JSON encoded map.

See the [updater tests](https://github.com/nuxt/vue-meta/blob/feat-add-non-component-info/test/utils/meta-info-data.js#L270) for an example:
```js
// data
metaInfo = {
  bodyAttr: { foo: 'bar', fizz: ['fuzz', 'fozz'] }
}

// ssr tag
<body foo="bar" fizz="fuzz fozz" data-vue-meta="%7B%22foo%22:%7B%22ssr%22:%22bar%22%7D,%22fizz%22:%7B%22ssr%22:%5B%22fuzz%22,%22fozz%22%5D%7D%7D">

// attribute map (values listed per app id)
{ bodyAttrs: {
  foo: { ssr: 'bar' },
  fizz: { ssr: ['fuzz', 'fozz'] }
}}
```

@Atinux nope, the old `body.text` syntax still exists. Probably will remove the need to call `.text` in the next major

**Comment by pimlie** [comment]
### Enable `refreshOnceOnNavigation` during runtime

Workaround for: https://github.com/nuxt/nuxt.js/issues/6330

One reason for this feature is that Nuxt.js doesnt allow configuring vue-meta plugin options at the moment. Now users can still enable this by calling 
```js
app.$meta().setOptions({ refreshOnceOnNavigation: true })
```

Its _not_ supported to remove the navigation guards.

**Comment by pimlie** [comment]
As I did it again (sorry, the pr grew a bit too big), please mainly review the concept/procedures of the new features. Below are the corresponding test-cases which probably show the supposed behaviour best.

Add additional metaInfo:
- https://github.com/nuxt/vue-meta/blob/feat-add-non-component-info/test/unit/components.test.js#L141-L159
- https://github.com/nuxt/vue-meta/blob/feat-add-non-component-info/test/unit/components.test.js#L391-L505

Injector helpers:
- https://github.com/nuxt/vue-meta/blob/feat-add-non-component-info/test/unit/generators.test.js#L113-L140

**Comment by pimlie** [comment]
### New option `debounceWait`

You can now configure for how long vue-meta debounces meta updates. The default value is `10`ms.

This option can be set during runtime:
```js
// debounce meta updates for 50ms 
app.$meta().setOptions({ debounceWait: 50 })
```

### New option `waitOnDestroyed`

Once a component is destroyed, vue-meta will update the meta information to make sure any info added by the destroyed component is removed. Default value is `true`

Previously this always  an interval of 50ms to make sure to wait until the element had been removed (due to transitions). If you set `waitOnDestroyed: false` then the destroyed update will always be called in the _nextTick_ instead.

> Note that destroyed updates are also debounced with other lifecycle hook updates

This option can be set during runtime:
```js
app.$meta().setOptions({ waitOnDestroyed: false })
```

**Comment by LuXDAmore** [comment]
I should try this new option.

> // debounce meta updates for 50ms 
> app.$meta().setOptions({ debounceWait: 50 })

IDK: `requestAnimationFrame()` could be a better default timing?

> The default value is 10ms.

**Comment by pimlie** [comment]
rAF was used previously but we switched back to timers. The issue with rAF is is that it is meant for graphical updates, ie Firefox can therefor decide sometimes to not run any rAF on _non-visible_ tabs. There have been bug reports about that because when you opened a new page on a new tab, then the title of the tab wont be set because Firefox doesnt run the rAF until the tab is visible.

**Pull request merged**
